# Memory-mapped corpus benchmark for FIQA dataset

dataset: fiqa
method: memmap  # custom memory-mapped implementation
params:
  buffer_size: 8388608  # 8MB buffer (8 * 1024 * 1024)
  cache_size: 50000    # LRU cache size
  compression_level: 1  # zlib compression level
  alignment: 16       # memory alignment in bytes

benchmark:
  warmup_queries: 100
  measure_memory: true
  measure_latency: true
  batch_sizes: [1, 10, 100, 1000]  # test different batch sizes
  access_patterns:
    - sequential      # test sequential access
    - random         # test random access
    - clustered      # test localized access patterns