# Default configuration for Lightning Retrieval integration tests

test_suites:
  - bm25
  - quantization 
  - memory_mapping
  - topk

parameters:
  # BM25 parameters
  bm25:
    k1: 1.2
    b: 0.75
    batch_size: 1000
    
  # Quantization parameters  
  quantization:
    test_sizes: [1000, 10000, 100000]
    embedding_dim: 768
    
  # Memory mapping parameters
  memory_mapping:
    num_docs: 50000
    avg_doc_length: 200
    batch_size: 1000
    
  # Top-K parameters
  topk:
    k_values: [10, 50, 100, 1000]
    array_sizes: [1000, 10000, 100000]

output_dir: "test_results"

# Enable hardware info collection
hardware_info: true

# Enable memory profiling 
memory_profiling: true