# RAG Research Pipeline - MS MARCO Dataset - All Sparse Methods
output_dir: "results"
experiments:
  - name: "msmarco_bm25_custom"
    dataset: "msmarco"
    retriever:
      type: "bm25_custom"
      model: null
      params:
        top_k: 100
        k1: 1.2
        b: 0.75
        use_numba: true
        cache_matrices: true
    reader:
      type: "extractive"
      params:
        max_answer_length: 200

  - name: "msmarco_dpr_sparse"
    dataset: "msmarco"
    retriever:
      type: "dpr"
      model: "sentence-transformers/facebook-dpr-question_encoder-single-nq-base"
      params:
        top_k: 100
        use_numba: true
        cache_matrices: true
    reader:
      type: "extractive"
      params:
        max_answer_length: 200

  - name: "msmarco_contriever_sparse"
    dataset: "msmarco"
    retriever:
      type: "contriever"
      model: "facebook/contriever"
      params:
        top_k: 100
        use_numba: true
        cache_matrices: true
    reader:
      type: "generative"
      params:
        max_context_length: 800

  - name: "msmarco_tfidf_sparse"
    dataset: "msmarco"
    retriever:
      type: "tfidf"
      model: null
      params:
        top_k: 100
        ngram_range: [1, 2]
        max_features: 100000
        use_numba: true
        cache_matrices: true
    reader:
      type: "extractive"
      params:
        max_answer_length: 200

  - name: "msmarco_bm25_optimized"
    dataset: "msmarco"
    retriever:
      type: "bm25_custom"
      model: null
      params:
        top_k: 100
        k1: 1.6
        b: 0.8
        use_numba: true
        cache_matrices: true
    reader:
      type: "generative"
      params:
        max_context_length: 800

  - name: "msmarco_ance_sparse"
    dataset: "msmarco"
    retriever:
      type: "ance"
      model: "sentence-transformers/msmarco-distilbert-base-tas-b"
      params:
        top_k: 100
        use_numba: true
        cache_matrices: true
    reader:
      type: "extractive"
      params:
        max_answer_length: 200

  - name: "msmarco_splade_sparse"
    dataset: "msmarco"
    retriever:
      type: "splade"
      model: "naver/splade-cocondenser-ensembledistil"
      params:
        top_k: 100
        use_numba: true
        cache_matrices: true
    reader:
      type: "generative"
      params:
        max_context_length: 800

  - name: "msmarco_hybrid_sparse"
    dataset: "msmarco"
    retriever:
      type: "hybrid"
      model: 
        sparse: "bm25_custom"
        dense: "sentence-transformers/msmarco-distilbert-base-tas-b"
      params:
        top_k: 100
        sparse_weight: 0.3
        dense_weight: 0.7
        use_numba: true
        cache_matrices: true
    reader:
      type: "generative"
      params:
        max_context_length: 800